name: Fetch cn_dicts

on:
  push:
    branches:
      - main  # 或者您想要触发的分支名称

jobs:
  fetch_cn_dicts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # 我们只需要最新的提交

      - name: Fetch cn_dicts folder
        uses: actions/checkout@v4
        with:
          repository: boomker/rime-fast-xhup
          path: temp_rime_fast_xhup
          sparse-checkout: |
            cn_dicts
          sparse-checkout-cone-mode: false

      - name: Move cn_dicts to root
        run: |
          mv temp_rime_fast_xhup/cn_dicts ./
          rm -rf temp_rime_fast_xhup

      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add cn_dicts
          git commit -m "Update cn_dicts from rime-fast-xhup" || exit 0
          git push
